export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE'
export const FETCHED_TEAMS = 'FETCHED_TEAMS'

export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE'
export const FETCHED_TEAM = 'FETCHED_TEAM'

export const GET_FIXTURES_REQUEST = 'GET_FIXTURES_REQUEST'
export const GET_FIXTURES_SUCCESS = 'GET_FIXTURES_SUCCESS'
export const GET_FIXTURES_FAILURE = 'GET_FIXTURES_FAILURE'
export const FETCHED_FIXTURES = 'FETCHED_FIXTURES'

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE'
export const FETCHED_EVENT = 'FETCHED_EVENT'

export const GET_STANDINGS_REQUEST = 'GET_STANDINGS_REQUEST'
export const GET_STANDINGS_SUCCESS = 'GET_STANDINGS_SUCCESS'
export const GET_STANDINGS_FAILURE = 'GET_STANDINGS_FAILURE'
export const FETCHED_STANDINGS = 'FETCHED_STANDINGS'

export const GET_ODDS_REQUEST = 'GET_ODDS_REQUEST'
export const GET_ODDS_SUCCESS = 'GET_ODDS_SUCCESS'
export const GET_ODDS_FAILURE = 'GET_ODDS_FAILURE'
export const FETCHED_ODDS = 'FETCHED_ODDS'

